### ISSUE TITLE
Behavior when multiple RPC URLs are specified for the same chain

### ISSUE THREAD

**Issue by ComfyGummy** [web3-protocol/web3protocol-js#2]
Hello,

I am wondering about what the behavior of the library is when multiple RPC URLs are specified for the same chain ID.
I can think of three possible behaviors:

1. Pick a random RPC URL and use that one.
2. Go through RPC URLs in order until the first one succeeds, and return that one.
3. Make a request in parallel to all RPC URLs, and return the first one that succeeds (cancel all the others in flight).

Option 3 seems like it would have the best user experience for browsing the web3 web. [This line](https://github.com/web3-protocol/web3protocol-js/blob/e91ac55bf47bfa449f23078a1fadf79e08c7782c/src/chains/index.js#L51) suggest that the current behavior is more likely option 1 or 2. Implementing option 3 would avoid the need to override the list of chain URLs.

It's possible to emulate option 3 by creating multiple `Client` instances with one RPC URL per chain ID specified in each, and then using them in parallel, but this feels hacky and something that the library should handle.

Is it possible to either add an option to do parallel requests, or to make it the default behavior of the library?

CG

**Comment by nand2** [comment]
Hi!

I'll admit, our Viem.sh ethereum client library was providing and handling arrays of RPC URLs, so I have mirrored this configuration, but until now did not know how it handled it.
It turns out that by default it [only take the first one](https://github.com/wevm/viem/blob/f9aa3af9a198a8d007b8be5eafc628e797ed0710/src/clients/transports/http.ts#L80), and ignore the rest.

I believe that by default we should go by the most intuitive, and the most intuitive would be the behavior 2. And because Viem is an awesome library, they provide this option ([Fallback transport](https://viem.sh/docs/clients/transports/fallback.html)) with extra functionality : 

> Transport Ranking enables each of the Transports passed to the fallback Transport are automatically ranked based on their latency & stability via a weighted moving score algorithm.
> Every 10 seconds (interval), the fallback Transport will ping each transport in the list. For the past 10 pings (sampleCount), they will be ranked based on if they responded (stability) and how fast they responded (latency). The algorithm applies a weight of 0.7 to the stability score, and a weight of 0.3 to the latency score to derive the final score which it is ranked on.

I believe this option will give the best web3 browsing experience. I will implement that.

**Comment by nand2** [comment]
Ok looks like I will have to skip Viem because, even though they are great, I would like more infos that they return, for example I cannot know if there was a fallback, and if yes, what was the error of the first RPC call. This is important to me as I want to be the more precise possible with web3curl in his verbose mode.

So I'll make a standard fallback mode first, and -- thinking more about it, the behavior 3 could be a good idea, I'll make it, but I believe standard fallback should be default.

**Comment by nand2** [comment]
Hi!

Ok to start things, I have published a new version which now handle multiple RPCs for a given chain, as a fallback list : if one RPC fails, it goes to the next. I will add the "all RPCs are called in parralel, the first answering one is taken" mode later as an option.

This made me bypass Viem for all calls, which give me the possibility to log much more; so I have also updated web3curl with more infos in verbose mode, especially on the name resolution part.

**Comment by ComfyGummy** [comment]
Thanks for the work!

**Comment by nand2** [comment]
Hi,
Ok I have added the parallel mode in version 0.4.4 just released!

It works as intended (first non-breaking RPC is used, not waiting for the others), the only issue so far is that other calls in-flight are not cancelled, so in short-lived apps that make a web3 call and returns right away (e.g. web3curl), even though the result is displayed and finished, it will end for all calls to finish before the app is terminated.

My guess is that most users will use this for long-lived apps (browser, extensions, ...) so I'll let it this way for now.
